### ISSUE TITLE
Not an issue: Need your assistance or advice

### ISSUE THREAD

**Issue by dev-itis-spk** [Matthew-Lancaster/Matthew-Lancaster#1]
Hello Matthew,
Can you please let me know how to make github treat vbs scripts as text files instead of binary files so that seeing the difference becomes easier.

Your help is highly appreciated.

Thanks

**Comment by Matthew-Lancaster** [comment]
HI PRADEEP .VBS FILE ARE TEXT -- THE TEXT WITH NOTEPAD++ EXAMPLE HERE IS NOTEPAD++ LOOK BOTTOM RIGHT CORNER UTF-8---------------------------------------------------------------------VBS 68-FILE LOCATOR -- SCRIPT -  RETEKESS.VBS
---------------------------------------------------------------------
VBS 68-FILE LOCATOR -- SCRIPT - RETEKESS.VBS 
HTTP://TINYURL.COM/UEF4GUH---------------------------------------------------------------------
THE .VBS UTF-8 UNI-CODE -- ARE NOT PLAIN TEXTAND THAT WILL TAKE SOME STUDY---------------------------------------------------------------------
AND .EXE ARE BINARY
A PICTURE IMAGE IS BINARYAS EXTENSION.VBS FILETHEY RECOGNISE AS TEXTNOT SURE YOU GIVE QUESTION COMPLEX OR SIMPLEHERE A SCRIPT IN .BAT LANGUAGEDO SOME SYNC BY GOODSYNC BEFORE AT ENDER IT RUN GIT HUB PROCESS FILE ALSO OF BATCH LANGUAGE ---------------------------------------------------------------------BAT 59-RUN GOODSYNC SET SCRIPTOR.BAT 
HTTP://TINYURL.COM/V3QR7GG ------------------------------------------------------------------------------------------------------------------------------------------HERE THE 2ND ROUTINE THAT SYNC TO GITHUB
AT LINE 231 BEGINNERTOOK HARD WORK ALL-NIGHTER 1ST EVENING ---------------------------------------------------------------------ALSO, USE THE APP DESKTOP VERSION GITHUB WHEN FIRST CREATE RESPODTORY
DO SOME CLONE IF BECOME BUGGER -- IF BIGG FILE GET IN THERETAKE A LONG WHILE AND RESET CLONE WAY AGAINTHE PASS KEY IS NOT THERE IS IN ANOTHER FILE OVER THAT WAYOPEN AND READ JUST BEFORE ---------------------------------------------------------------------BAT 45-SCRIPT RUN GITHUB.BAT 
HTTP://TINYURL.COM/V6R9PFD ---------------------------------------------------------------------OVER AND ON~
 Mon 13-Apr-2020 17:01:15Text Size  1806 -- CRC32 DE91103



    On Monday, 13 April 2020, 16:09:50 BST, Pradeep Kumar S <notifications@github.com> wrote:  
 
 


Hello Matthew,
Can you please let me know how to make github treat vbs scripts as text files instead of binary files so that seeing the difference becomes easier.

Your help is highly appreciated.

Thanks

**Comment by Matthew-Lancaster** [comment]
HI PRADEEP 
.VBS FILE ARE TEXT -- THE TEXT WITH NOTEPAD++ 
EXAMPLE HERE IS NOTEPAD++ LOOK BOTTOM RIGHT CORNER UTF-8
---------------------------------------------------------------------
VBS 68-FILE LOCATOR -- SCRIPT - RETEKESS.VBS 
HTTP://TINYURL.COM/UEF4GUH
---------------------------------------------------------------------
THE .VBS UTF-8 UNI-CODE -- ARE NOT PLAIN TEXT
AND THAT WILL TAKE SOME STUDY
---------------------------------------------------------------------
AND .EXE ARE BINARY
A PICTURE IMAGE IS BINARY
AS EXTENSION
.VBS FILE
THEY RECOGNISE AS TEXT
NOT SURE YOU GIVE QUESTION COMPLEX OR SIMPLE
HERE A SCRIPT IN .BAT LANGUAGE
DO SOME SYNC BY GOODSYNC BEFORE AT ENDER IT RUN GITHUB PROCESS FILE ALSO OF BATCH LANGUAGE
---------------------------------------------------------------------
BAT 59-RUN GOODSYNC SET SCRIPTOR.BAT 
HTTP://TINYURL.COM/V3QR7GG
---------------------------------------------------------------------
---------------------------------------------------------------------
HERE THE 2ND ROUTINE THAT SYNC TO GITHUB
AT LINE 231 BEGINNER
TOOK HARD WORK ALL-NIGHTER 1ST EVENING
---------------------------------------------------------------------
ALSO, USE THE APP DESKTOP VERSION GITHUB WHEN FIRST CREATE REPOSITORIES DO SOME CLONE 
IF BECOME BUGGER -- IF BIGG FILE GET IN THERE
TAKE A LONG WHILE AND RESET CLONE WAY AGAIN
THE PASS KEY IS NOT THERE IS IN ANOTHER FILE OVER THAT WAY
OPEN AND READ JUST BEFORE
---------------------------------------------------------------------
BAT 45-SCRIPT RUN GITHUB.BAT 
HTTP://TINYURL.COM/V6R9PFD
---------------------------------------------------------------------
----------
----------
---------------------------------------------------------------------
OVER AND ON
~
Mon 13-Apr-2020 17:01:15
Mon 13-Apr-2020 17:14:00
Text Size  1806 -- CRC32 DE91103
Text Size  1783 -- CRC32 E70920FA

**Comment by dev-itis-spk** [comment]
Thanks for your Valuable feedback Matthew. It was of great help.
Closing this issue.
Appreciate your assistance.
